# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedembeds',
            name='html',
            field=models.CharField(max_length=600),
        ),
    ]
